// <auto-generated />
using System;
using BBBorderBox.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBBorderBox.Data.Migrations
{
    [DbContext(typeof(BBBorderBoxContext))]
    [Migration("20220322014823_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BBBorderBox.Entity.WServices.ChatUpdate", b =>
                {
                    b.Property<long>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UpdateId"), 1L, 1);

                    b.Property<long>("AppUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME");

                    b.Property<long>("EmployId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedHuman")
                        .HasColumnType("bit");

                    b.Property<string>("ReturnResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TalkingWithHuman")
                        .HasColumnType("bit");

                    b.Property<string>("TypedCommand")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UpdateId")
                        .HasName("PK_ChatsUpdates_UpdateId");

                    b.ToTable("ChatsUpdates", "Telegram");
                });
#pragma warning restore 612, 618
        }
    }
}
