// <auto-generated />
using System;
using BBBorderBox.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBBorderBox.Data.Migrations
{
    [DbContext(typeof(BBBorderBoxContext))]
    [Migration("20220420012252_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BBBorderBox.Entity.Data.Common.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"), 1L, 1);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(70)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("StrKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2)");

                    b.HasKey("CountryId")
                        .HasName("PK_Countries_CountryId");

                    b.HasIndex("StrKey")
                        .IsUnique();

                    b.ToTable("Countries", "Common");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "NDORRA",
                            IsActive = false,
                            StrKey = "AD"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "NITED ARAB EMIRATES",
                            IsActive = false,
                            StrKey = "AE"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "FGHANISTAN",
                            IsActive = false,
                            StrKey = "AF"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = "NTIGUA AND BARBUDA",
                            IsActive = false,
                            StrKey = "AG"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryName = "NGUILLA",
                            IsActive = false,
                            StrKey = "AI"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryName = "LBANIA",
                            IsActive = false,
                            StrKey = "AL"
                        },
                        new
                        {
                            CountryId = 7,
                            CountryName = "RMENIA",
                            IsActive = false,
                            StrKey = "AM"
                        },
                        new
                        {
                            CountryId = 8,
                            CountryName = "NGOLA",
                            IsActive = false,
                            StrKey = "AO"
                        },
                        new
                        {
                            CountryId = 9,
                            CountryName = "NTARCTICA",
                            IsActive = false,
                            StrKey = "AQ"
                        },
                        new
                        {
                            CountryId = 10,
                            CountryName = "RGENTINA",
                            IsActive = false,
                            StrKey = "AR"
                        },
                        new
                        {
                            CountryId = 11,
                            CountryName = "MERICAN SAMOA",
                            IsActive = false,
                            StrKey = "AS"
                        },
                        new
                        {
                            CountryId = 12,
                            CountryName = "USTRIA",
                            IsActive = false,
                            StrKey = "AT"
                        },
                        new
                        {
                            CountryId = 13,
                            CountryName = "USTRALIA",
                            IsActive = false,
                            StrKey = "AU"
                        },
                        new
                        {
                            CountryId = 14,
                            CountryName = "RUBA",
                            IsActive = false,
                            StrKey = "AW"
                        },
                        new
                        {
                            CountryId = 15,
                            CountryName = "LAND ISLANDS",
                            IsActive = false,
                            StrKey = "AX"
                        },
                        new
                        {
                            CountryId = 16,
                            CountryName = "ZERBAIJAN",
                            IsActive = false,
                            StrKey = "AZ"
                        },
                        new
                        {
                            CountryId = 17,
                            CountryName = "OSNIA AND HERZEGOVINA",
                            IsActive = false,
                            StrKey = "BA"
                        },
                        new
                        {
                            CountryId = 18,
                            CountryName = "ARBADOS",
                            IsActive = false,
                            StrKey = "BB"
                        },
                        new
                        {
                            CountryId = 19,
                            CountryName = "ANGLADESH",
                            IsActive = false,
                            StrKey = "BD"
                        },
                        new
                        {
                            CountryId = 20,
                            CountryName = "ELGIUM",
                            IsActive = false,
                            StrKey = "BE"
                        },
                        new
                        {
                            CountryId = 21,
                            CountryName = "URKINA FASO",
                            IsActive = false,
                            StrKey = "BF"
                        },
                        new
                        {
                            CountryId = 22,
                            CountryName = "ULGARIA",
                            IsActive = false,
                            StrKey = "BG"
                        },
                        new
                        {
                            CountryId = 23,
                            CountryName = "AHRAIN",
                            IsActive = false,
                            StrKey = "BH"
                        },
                        new
                        {
                            CountryId = 24,
                            CountryName = "URUNDI",
                            IsActive = false,
                            StrKey = "BI"
                        },
                        new
                        {
                            CountryId = 25,
                            CountryName = "ENIN",
                            IsActive = false,
                            StrKey = "BJ"
                        },
                        new
                        {
                            CountryId = 26,
                            CountryName = "AINT BARTHÉLEMY",
                            IsActive = false,
                            StrKey = "BL"
                        },
                        new
                        {
                            CountryId = 27,
                            CountryName = "ERMUDA",
                            IsActive = false,
                            StrKey = "BM"
                        },
                        new
                        {
                            CountryId = 28,
                            CountryName = "RUNEI DARUSSALAM",
                            IsActive = false,
                            StrKey = "BN"
                        },
                        new
                        {
                            CountryId = 29,
                            CountryName = "OLIVIA (PLURINATIONAL STATE OF)",
                            IsActive = false,
                            StrKey = "BO"
                        },
                        new
                        {
                            CountryId = 30,
                            CountryName = "ONAIRE, SINT EUSTATIUS AND SABA",
                            IsActive = false,
                            StrKey = "BQ"
                        },
                        new
                        {
                            CountryId = 31,
                            CountryName = "RAZIL",
                            IsActive = false,
                            StrKey = "BR"
                        },
                        new
                        {
                            CountryId = 32,
                            CountryName = "AHAMAS",
                            IsActive = false,
                            StrKey = "BS"
                        },
                        new
                        {
                            CountryId = 33,
                            CountryName = "HUTAN",
                            IsActive = false,
                            StrKey = "BT"
                        },
                        new
                        {
                            CountryId = 34,
                            CountryName = "OUVET ISLAND",
                            IsActive = false,
                            StrKey = "BV"
                        },
                        new
                        {
                            CountryId = 35,
                            CountryName = "OTSWANA",
                            IsActive = false,
                            StrKey = "BW"
                        },
                        new
                        {
                            CountryId = 36,
                            CountryName = "ELARUS",
                            IsActive = false,
                            StrKey = "BY"
                        },
                        new
                        {
                            CountryId = 37,
                            CountryName = "ELIZE",
                            IsActive = false,
                            StrKey = "BZ"
                        },
                        new
                        {
                            CountryId = 38,
                            CountryName = "ANADA",
                            IsActive = false,
                            StrKey = "CA"
                        },
                        new
                        {
                            CountryId = 39,
                            CountryName = "OCOS (KEELING) ISLANDS",
                            IsActive = false,
                            StrKey = "CC"
                        },
                        new
                        {
                            CountryId = 40,
                            CountryName = "ONGO, DEMOCRATIC REPUBLIC OF THE",
                            IsActive = false,
                            StrKey = "CD"
                        },
                        new
                        {
                            CountryId = 41,
                            CountryName = "ENTRAL AFRICAN REPUBLIC",
                            IsActive = false,
                            StrKey = "CF"
                        },
                        new
                        {
                            CountryId = 42,
                            CountryName = "ONGO",
                            IsActive = false,
                            StrKey = "CG"
                        },
                        new
                        {
                            CountryId = 43,
                            CountryName = "WITZERLAND",
                            IsActive = false,
                            StrKey = "CH"
                        },
                        new
                        {
                            CountryId = 44,
                            CountryName = "ÔTE D''IVOIRE",
                            IsActive = false,
                            StrKey = "CI"
                        },
                        new
                        {
                            CountryId = 45,
                            CountryName = "COOK ISLANDS",
                            IsActive = false,
                            StrKey = "CK"
                        },
                        new
                        {
                            CountryId = 46,
                            CountryName = "CHILE",
                            IsActive = false,
                            StrKey = "CL"
                        },
                        new
                        {
                            CountryId = 47,
                            CountryName = "CAMEROON",
                            IsActive = false,
                            StrKey = "CM"
                        },
                        new
                        {
                            CountryId = 48,
                            CountryName = "CHINA",
                            IsActive = false,
                            StrKey = "CN"
                        },
                        new
                        {
                            CountryId = 49,
                            CountryName = "COLOMBIA",
                            IsActive = false,
                            StrKey = "CO"
                        },
                        new
                        {
                            CountryId = 50,
                            CountryName = "COSTA RICA",
                            IsActive = false,
                            StrKey = "CR"
                        },
                        new
                        {
                            CountryId = 51,
                            CountryName = "CUBA",
                            IsActive = false,
                            StrKey = "CU"
                        },
                        new
                        {
                            CountryId = 52,
                            CountryName = "CABO VERDE",
                            IsActive = false,
                            StrKey = "CV"
                        },
                        new
                        {
                            CountryId = 53,
                            CountryName = "CURAÇAO",
                            IsActive = false,
                            StrKey = "CW"
                        },
                        new
                        {
                            CountryId = 54,
                            CountryName = "CHRISTMAS ISLAND",
                            IsActive = false,
                            StrKey = "CX"
                        },
                        new
                        {
                            CountryId = 55,
                            CountryName = "CYPRUS",
                            IsActive = false,
                            StrKey = "CY"
                        },
                        new
                        {
                            CountryId = 56,
                            CountryName = "CZECHIA",
                            IsActive = false,
                            StrKey = "CZ"
                        },
                        new
                        {
                            CountryId = 57,
                            CountryName = "GERMANY",
                            IsActive = false,
                            StrKey = "DE"
                        },
                        new
                        {
                            CountryId = 58,
                            CountryName = "DJIBOUTI",
                            IsActive = false,
                            StrKey = "DJ"
                        },
                        new
                        {
                            CountryId = 59,
                            CountryName = "DENMARK",
                            IsActive = false,
                            StrKey = "DK"
                        },
                        new
                        {
                            CountryId = 60,
                            CountryName = "DOMINICA",
                            IsActive = false,
                            StrKey = "DM"
                        },
                        new
                        {
                            CountryId = 61,
                            CountryName = "DOMINICAN REPUBLIC",
                            IsActive = false,
                            StrKey = "DO"
                        },
                        new
                        {
                            CountryId = 62,
                            CountryName = "ALGERIA",
                            IsActive = false,
                            StrKey = "DZ"
                        },
                        new
                        {
                            CountryId = 63,
                            CountryName = "ECUADOR",
                            IsActive = false,
                            StrKey = "EC"
                        },
                        new
                        {
                            CountryId = 64,
                            CountryName = "ESTONIA",
                            IsActive = false,
                            StrKey = "EE"
                        },
                        new
                        {
                            CountryId = 65,
                            CountryName = "EGYPT",
                            IsActive = false,
                            StrKey = "EG"
                        },
                        new
                        {
                            CountryId = 66,
                            CountryName = "WESTERN SAHARA",
                            IsActive = false,
                            StrKey = "EH"
                        },
                        new
                        {
                            CountryId = 67,
                            CountryName = "ERITREA",
                            IsActive = false,
                            StrKey = "ER"
                        },
                        new
                        {
                            CountryId = 68,
                            CountryName = "SPAIN",
                            IsActive = false,
                            StrKey = "ES"
                        },
                        new
                        {
                            CountryId = 69,
                            CountryName = "ETHIOPIA",
                            IsActive = false,
                            StrKey = "ET"
                        },
                        new
                        {
                            CountryId = 70,
                            CountryName = "FINLAND",
                            IsActive = false,
                            StrKey = "FI"
                        },
                        new
                        {
                            CountryId = 71,
                            CountryName = "FIJI",
                            IsActive = false,
                            StrKey = "FJ"
                        },
                        new
                        {
                            CountryId = 72,
                            CountryName = "FALKLAND ISLANDS (MALVINAS)",
                            IsActive = false,
                            StrKey = "FK"
                        },
                        new
                        {
                            CountryId = 73,
                            CountryName = "MICRONESIA (FEDERATED STATES OF)",
                            IsActive = false,
                            StrKey = "FM"
                        },
                        new
                        {
                            CountryId = 74,
                            CountryName = "FAROE ISLANDS",
                            IsActive = false,
                            StrKey = "FO"
                        },
                        new
                        {
                            CountryId = 75,
                            CountryName = "FRANCE",
                            IsActive = false,
                            StrKey = "FR"
                        },
                        new
                        {
                            CountryId = 76,
                            CountryName = "GABON",
                            IsActive = false,
                            StrKey = "GA"
                        },
                        new
                        {
                            CountryId = 77,
                            CountryName = "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND",
                            IsActive = false,
                            StrKey = "GB"
                        },
                        new
                        {
                            CountryId = 78,
                            CountryName = "GRENADA",
                            IsActive = false,
                            StrKey = "GD"
                        },
                        new
                        {
                            CountryId = 79,
                            CountryName = "GEORGIA",
                            IsActive = false,
                            StrKey = "GE"
                        },
                        new
                        {
                            CountryId = 80,
                            CountryName = "FRENCH GUIANA",
                            IsActive = false,
                            StrKey = "GF"
                        },
                        new
                        {
                            CountryId = 81,
                            CountryName = "GUERNSEY",
                            IsActive = false,
                            StrKey = "GG"
                        },
                        new
                        {
                            CountryId = 82,
                            CountryName = "GHANA",
                            IsActive = false,
                            StrKey = "GH"
                        },
                        new
                        {
                            CountryId = 83,
                            CountryName = "GIBRALTAR",
                            IsActive = false,
                            StrKey = "GI"
                        },
                        new
                        {
                            CountryId = 84,
                            CountryName = "GREENLAND",
                            IsActive = false,
                            StrKey = "GL"
                        },
                        new
                        {
                            CountryId = 85,
                            CountryName = "GAMBIA",
                            IsActive = false,
                            StrKey = "GM"
                        },
                        new
                        {
                            CountryId = 86,
                            CountryName = "GUINEA",
                            IsActive = false,
                            StrKey = "GN"
                        },
                        new
                        {
                            CountryId = 87,
                            CountryName = "GUADELOUPE",
                            IsActive = false,
                            StrKey = "GP"
                        },
                        new
                        {
                            CountryId = 88,
                            CountryName = "EQUATORIAL GUINEA",
                            IsActive = false,
                            StrKey = "GQ"
                        },
                        new
                        {
                            CountryId = 89,
                            CountryName = "GREECE",
                            IsActive = false,
                            StrKey = "GR"
                        },
                        new
                        {
                            CountryId = 90,
                            CountryName = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
                            IsActive = false,
                            StrKey = "GS"
                        },
                        new
                        {
                            CountryId = 91,
                            CountryName = "GUATEMALA",
                            IsActive = false,
                            StrKey = "GT"
                        },
                        new
                        {
                            CountryId = 92,
                            CountryName = "GUAM",
                            IsActive = false,
                            StrKey = "GU"
                        },
                        new
                        {
                            CountryId = 93,
                            CountryName = "GUINEA-BISSAU",
                            IsActive = false,
                            StrKey = "GW"
                        },
                        new
                        {
                            CountryId = 94,
                            CountryName = "GUYANA",
                            IsActive = false,
                            StrKey = "GY"
                        },
                        new
                        {
                            CountryId = 95,
                            CountryName = "HONG KONG",
                            IsActive = false,
                            StrKey = "HK"
                        },
                        new
                        {
                            CountryId = 96,
                            CountryName = "HEARD ISLAND AND MCDONALD ISLANDS",
                            IsActive = false,
                            StrKey = "HM"
                        },
                        new
                        {
                            CountryId = 97,
                            CountryName = "HONDURAS",
                            IsActive = false,
                            StrKey = "HN"
                        },
                        new
                        {
                            CountryId = 98,
                            CountryName = "CROATIA",
                            IsActive = false,
                            StrKey = "HR"
                        },
                        new
                        {
                            CountryId = 99,
                            CountryName = "HAITI",
                            IsActive = false,
                            StrKey = "HT"
                        },
                        new
                        {
                            CountryId = 100,
                            CountryName = "HUNGARY",
                            IsActive = false,
                            StrKey = "HU"
                        },
                        new
                        {
                            CountryId = 101,
                            CountryName = "INDONESIA",
                            IsActive = false,
                            StrKey = "ID"
                        },
                        new
                        {
                            CountryId = 102,
                            CountryName = "IRELAND",
                            IsActive = false,
                            StrKey = "IE"
                        },
                        new
                        {
                            CountryId = 103,
                            CountryName = "ISRAEL",
                            IsActive = false,
                            StrKey = "IL"
                        },
                        new
                        {
                            CountryId = 104,
                            CountryName = "ISLE OF MAN",
                            IsActive = false,
                            StrKey = "IM"
                        },
                        new
                        {
                            CountryId = 105,
                            CountryName = "INDIA",
                            IsActive = false,
                            StrKey = "IN"
                        },
                        new
                        {
                            CountryId = 106,
                            CountryName = "BRITISH INDIAN OCEAN TERRITORY",
                            IsActive = false,
                            StrKey = "IO"
                        },
                        new
                        {
                            CountryId = 107,
                            CountryName = "IRAQ",
                            IsActive = false,
                            StrKey = "IQ"
                        },
                        new
                        {
                            CountryId = 108,
                            CountryName = "IRAN (ISLAMIC REPUBLIC OF)",
                            IsActive = false,
                            StrKey = "IR"
                        },
                        new
                        {
                            CountryId = 109,
                            CountryName = "ICELAND",
                            IsActive = false,
                            StrKey = "IS"
                        },
                        new
                        {
                            CountryId = 110,
                            CountryName = "ITALY",
                            IsActive = false,
                            StrKey = "IT"
                        },
                        new
                        {
                            CountryId = 111,
                            CountryName = "JERSEY",
                            IsActive = false,
                            StrKey = "JE"
                        },
                        new
                        {
                            CountryId = 112,
                            CountryName = "JAMAICA",
                            IsActive = false,
                            StrKey = "JM"
                        },
                        new
                        {
                            CountryId = 113,
                            CountryName = "JORDAN",
                            IsActive = false,
                            StrKey = "JO"
                        },
                        new
                        {
                            CountryId = 114,
                            CountryName = "JAPAN",
                            IsActive = false,
                            StrKey = "JP"
                        },
                        new
                        {
                            CountryId = 115,
                            CountryName = "KENYA",
                            IsActive = false,
                            StrKey = "KE"
                        },
                        new
                        {
                            CountryId = 116,
                            CountryName = "KYRGYZSTAN",
                            IsActive = false,
                            StrKey = "KG"
                        },
                        new
                        {
                            CountryId = 117,
                            CountryName = "CAMBODIA",
                            IsActive = false,
                            StrKey = "KH"
                        },
                        new
                        {
                            CountryId = 118,
                            CountryName = "KIRIBATI",
                            IsActive = false,
                            StrKey = "KI"
                        },
                        new
                        {
                            CountryId = 119,
                            CountryName = "COMOROS",
                            IsActive = false,
                            StrKey = "KM"
                        },
                        new
                        {
                            CountryId = 120,
                            CountryName = "SAINT KITTS AND NEVIS",
                            IsActive = false,
                            StrKey = "KN"
                        },
                        new
                        {
                            CountryId = 121,
                            CountryName = "KOREA (DEMOCRATIC PEOPLE''S REPUBLIC OF)",
                            IsActive = false,
                            StrKey = "KP"
                        },
                        new
                        {
                            CountryId = 122,
                            CountryName = "KOREA, REPUBLIC OF",
                            IsActive = false,
                            StrKey = "KR"
                        },
                        new
                        {
                            CountryId = 123,
                            CountryName = "KUWAIT",
                            IsActive = false,
                            StrKey = "KW"
                        },
                        new
                        {
                            CountryId = 124,
                            CountryName = "CAYMAN ISLANDS",
                            IsActive = false,
                            StrKey = "KY"
                        },
                        new
                        {
                            CountryId = 125,
                            CountryName = "KAZAKHSTAN",
                            IsActive = false,
                            StrKey = "KZ"
                        },
                        new
                        {
                            CountryId = 126,
                            CountryName = "LAO PEOPLE''S DEMOCRATIC REPUBLIC",
                            IsActive = false,
                            StrKey = "LA"
                        },
                        new
                        {
                            CountryId = 127,
                            CountryName = "LEBANON",
                            IsActive = false,
                            StrKey = "LB"
                        },
                        new
                        {
                            CountryId = 128,
                            CountryName = "SAINT LUCIA",
                            IsActive = false,
                            StrKey = "LC"
                        },
                        new
                        {
                            CountryId = 129,
                            CountryName = "LIECHTENSTEIN",
                            IsActive = false,
                            StrKey = "LI"
                        },
                        new
                        {
                            CountryId = 130,
                            CountryName = "SRI LANKA",
                            IsActive = false,
                            StrKey = "LK"
                        },
                        new
                        {
                            CountryId = 131,
                            CountryName = "LIBERIA",
                            IsActive = false,
                            StrKey = "LR"
                        },
                        new
                        {
                            CountryId = 132,
                            CountryName = "LESOTHO",
                            IsActive = false,
                            StrKey = "LS"
                        },
                        new
                        {
                            CountryId = 133,
                            CountryName = "LITHUANIA",
                            IsActive = false,
                            StrKey = "LT"
                        },
                        new
                        {
                            CountryId = 134,
                            CountryName = "LUXEMBOURG",
                            IsActive = false,
                            StrKey = "LU"
                        },
                        new
                        {
                            CountryId = 135,
                            CountryName = "LATVIA",
                            IsActive = false,
                            StrKey = "LV"
                        },
                        new
                        {
                            CountryId = 136,
                            CountryName = "LIBYA",
                            IsActive = false,
                            StrKey = "LY"
                        },
                        new
                        {
                            CountryId = 137,
                            CountryName = "MOROCCO",
                            IsActive = false,
                            StrKey = "MA"
                        },
                        new
                        {
                            CountryId = 138,
                            CountryName = "MONACO",
                            IsActive = false,
                            StrKey = "MC"
                        },
                        new
                        {
                            CountryId = 139,
                            CountryName = "MOLDOVA, REPUBLIC OF",
                            IsActive = false,
                            StrKey = "MD"
                        },
                        new
                        {
                            CountryId = 140,
                            CountryName = "MONTENEGRO",
                            IsActive = false,
                            StrKey = "ME"
                        },
                        new
                        {
                            CountryId = 141,
                            CountryName = "SAINT MARTIN (FRENCH PART)",
                            IsActive = false,
                            StrKey = "MF"
                        },
                        new
                        {
                            CountryId = 142,
                            CountryName = "MADAGASCAR",
                            IsActive = false,
                            StrKey = "MG"
                        },
                        new
                        {
                            CountryId = 143,
                            CountryName = "MARSHALL ISLANDS",
                            IsActive = false,
                            StrKey = "MH"
                        },
                        new
                        {
                            CountryId = 144,
                            CountryName = "NORTH MACEDONIA",
                            IsActive = false,
                            StrKey = "MK"
                        },
                        new
                        {
                            CountryId = 145,
                            CountryName = "MALI",
                            IsActive = false,
                            StrKey = "ML"
                        },
                        new
                        {
                            CountryId = 146,
                            CountryName = "MYANMAR",
                            IsActive = false,
                            StrKey = "MM"
                        },
                        new
                        {
                            CountryId = 147,
                            CountryName = "MONGOLIA",
                            IsActive = false,
                            StrKey = "MN"
                        },
                        new
                        {
                            CountryId = 148,
                            CountryName = "MACAO",
                            IsActive = false,
                            StrKey = "MO"
                        },
                        new
                        {
                            CountryId = 149,
                            CountryName = "NORTHERN MARIANA ISLANDS",
                            IsActive = false,
                            StrKey = "MP"
                        },
                        new
                        {
                            CountryId = 150,
                            CountryName = "MARTINIQUE",
                            IsActive = false,
                            StrKey = "MQ"
                        },
                        new
                        {
                            CountryId = 151,
                            CountryName = "MAURITANIA",
                            IsActive = false,
                            StrKey = "MR"
                        },
                        new
                        {
                            CountryId = 152,
                            CountryName = "MONTSERRAT",
                            IsActive = false,
                            StrKey = "MS"
                        },
                        new
                        {
                            CountryId = 153,
                            CountryName = "MALTA",
                            IsActive = false,
                            StrKey = "MT"
                        },
                        new
                        {
                            CountryId = 154,
                            CountryName = "MAURITIUS",
                            IsActive = false,
                            StrKey = "MU"
                        },
                        new
                        {
                            CountryId = 155,
                            CountryName = "MALDIVES",
                            IsActive = false,
                            StrKey = "MV"
                        },
                        new
                        {
                            CountryId = 156,
                            CountryName = "MALAWI",
                            IsActive = false,
                            StrKey = "MW"
                        },
                        new
                        {
                            CountryId = 157,
                            CountryName = "MEXICO",
                            IsActive = true,
                            StrKey = "MX"
                        },
                        new
                        {
                            CountryId = 158,
                            CountryName = "MALAYSIA",
                            IsActive = false,
                            StrKey = "MY"
                        },
                        new
                        {
                            CountryId = 159,
                            CountryName = "MOZAMBIQUE",
                            IsActive = false,
                            StrKey = "MZ"
                        },
                        new
                        {
                            CountryId = 160,
                            CountryName = "NAMIBIA",
                            IsActive = false,
                            StrKey = "NA"
                        },
                        new
                        {
                            CountryId = 161,
                            CountryName = "NEW CALEDONIA",
                            IsActive = false,
                            StrKey = "NC"
                        },
                        new
                        {
                            CountryId = 162,
                            CountryName = "NIGER",
                            IsActive = false,
                            StrKey = "NE"
                        },
                        new
                        {
                            CountryId = 163,
                            CountryName = "NORFOLK ISLAND",
                            IsActive = false,
                            StrKey = "NF"
                        },
                        new
                        {
                            CountryId = 164,
                            CountryName = "NIGERIA",
                            IsActive = false,
                            StrKey = "NG"
                        },
                        new
                        {
                            CountryId = 165,
                            CountryName = "NICARAGUA",
                            IsActive = false,
                            StrKey = "NI"
                        },
                        new
                        {
                            CountryId = 166,
                            CountryName = "NETHERLANDS",
                            IsActive = false,
                            StrKey = "NL"
                        },
                        new
                        {
                            CountryId = 167,
                            CountryName = "NORWAY",
                            IsActive = false,
                            StrKey = "NO"
                        },
                        new
                        {
                            CountryId = 168,
                            CountryName = "NEPAL",
                            IsActive = false,
                            StrKey = "NP"
                        },
                        new
                        {
                            CountryId = 169,
                            CountryName = "NAURU",
                            IsActive = false,
                            StrKey = "NR"
                        },
                        new
                        {
                            CountryId = 170,
                            CountryName = "NIUE",
                            IsActive = false,
                            StrKey = "NU"
                        },
                        new
                        {
                            CountryId = 171,
                            CountryName = "NEW ZEALAND",
                            IsActive = false,
                            StrKey = "NZ"
                        },
                        new
                        {
                            CountryId = 172,
                            CountryName = "OMAN",
                            IsActive = false,
                            StrKey = "OM"
                        },
                        new
                        {
                            CountryId = 173,
                            CountryName = "PANAMA",
                            IsActive = false,
                            StrKey = "PA"
                        },
                        new
                        {
                            CountryId = 174,
                            CountryName = "PERU",
                            IsActive = false,
                            StrKey = "PE"
                        },
                        new
                        {
                            CountryId = 175,
                            CountryName = "FRENCH POLYNESIA",
                            IsActive = false,
                            StrKey = "PF"
                        },
                        new
                        {
                            CountryId = 176,
                            CountryName = "PAPUA NEW GUINEA",
                            IsActive = false,
                            StrKey = "PG"
                        },
                        new
                        {
                            CountryId = 177,
                            CountryName = "PHILIPPINES",
                            IsActive = false,
                            StrKey = "PH"
                        },
                        new
                        {
                            CountryId = 178,
                            CountryName = "PAKISTAN",
                            IsActive = false,
                            StrKey = "PK"
                        },
                        new
                        {
                            CountryId = 179,
                            CountryName = "POLAND",
                            IsActive = false,
                            StrKey = "PL"
                        },
                        new
                        {
                            CountryId = 180,
                            CountryName = "SAINT PIERRE AND MIQUELON",
                            IsActive = false,
                            StrKey = "PM"
                        },
                        new
                        {
                            CountryId = 181,
                            CountryName = "PITCAIRN",
                            IsActive = false,
                            StrKey = "PN"
                        },
                        new
                        {
                            CountryId = 182,
                            CountryName = "PUERTO RICO",
                            IsActive = false,
                            StrKey = "PR"
                        },
                        new
                        {
                            CountryId = 183,
                            CountryName = "PALESTINE, STATE OF",
                            IsActive = false,
                            StrKey = "PS"
                        },
                        new
                        {
                            CountryId = 184,
                            CountryName = "PORTUGAL",
                            IsActive = false,
                            StrKey = "PT"
                        },
                        new
                        {
                            CountryId = 185,
                            CountryName = "PALAU",
                            IsActive = false,
                            StrKey = "PW"
                        },
                        new
                        {
                            CountryId = 186,
                            CountryName = "PARAGUAY",
                            IsActive = false,
                            StrKey = "PY"
                        },
                        new
                        {
                            CountryId = 187,
                            CountryName = "QATAR",
                            IsActive = false,
                            StrKey = "QA"
                        },
                        new
                        {
                            CountryId = 188,
                            CountryName = "RÉUNION",
                            IsActive = false,
                            StrKey = "RE"
                        },
                        new
                        {
                            CountryId = 189,
                            CountryName = "ROMANIA",
                            IsActive = false,
                            StrKey = "RO"
                        },
                        new
                        {
                            CountryId = 190,
                            CountryName = "SERBIA",
                            IsActive = false,
                            StrKey = "RS"
                        },
                        new
                        {
                            CountryId = 191,
                            CountryName = "RUSSIAN FEDERATION",
                            IsActive = false,
                            StrKey = "RU"
                        },
                        new
                        {
                            CountryId = 192,
                            CountryName = "RWANDA",
                            IsActive = false,
                            StrKey = "RW"
                        },
                        new
                        {
                            CountryId = 193,
                            CountryName = "SAUDI ARABIA",
                            IsActive = false,
                            StrKey = "SA"
                        },
                        new
                        {
                            CountryId = 194,
                            CountryName = "SOLOMON ISLANDS",
                            IsActive = false,
                            StrKey = "SB"
                        },
                        new
                        {
                            CountryId = 195,
                            CountryName = "SEYCHELLES",
                            IsActive = false,
                            StrKey = "SC"
                        },
                        new
                        {
                            CountryId = 196,
                            CountryName = "SUDAN",
                            IsActive = false,
                            StrKey = "SD"
                        },
                        new
                        {
                            CountryId = 197,
                            CountryName = "SWEDEN",
                            IsActive = false,
                            StrKey = "SE"
                        },
                        new
                        {
                            CountryId = 198,
                            CountryName = "SINGAPORE",
                            IsActive = false,
                            StrKey = "SG"
                        },
                        new
                        {
                            CountryId = 199,
                            CountryName = "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
                            IsActive = false,
                            StrKey = "SH"
                        },
                        new
                        {
                            CountryId = 200,
                            CountryName = "SLOVENIA",
                            IsActive = false,
                            StrKey = "SI"
                        },
                        new
                        {
                            CountryId = 201,
                            CountryName = "SVALBARD AND JAN MAYEN",
                            IsActive = false,
                            StrKey = "SJ"
                        },
                        new
                        {
                            CountryId = 202,
                            CountryName = "SLOVAKIA",
                            IsActive = false,
                            StrKey = "SK"
                        },
                        new
                        {
                            CountryId = 203,
                            CountryName = "SIERRA LEONE",
                            IsActive = false,
                            StrKey = "SL"
                        },
                        new
                        {
                            CountryId = 204,
                            CountryName = "SAN MARINO",
                            IsActive = false,
                            StrKey = "SM"
                        },
                        new
                        {
                            CountryId = 205,
                            CountryName = "SENEGAL",
                            IsActive = false,
                            StrKey = "SN"
                        },
                        new
                        {
                            CountryId = 206,
                            CountryName = "SOMALIA",
                            IsActive = false,
                            StrKey = "SO"
                        },
                        new
                        {
                            CountryId = 207,
                            CountryName = "SURINAME",
                            IsActive = false,
                            StrKey = "SR"
                        },
                        new
                        {
                            CountryId = 208,
                            CountryName = "SOUTH SUDAN",
                            IsActive = false,
                            StrKey = "SS"
                        },
                        new
                        {
                            CountryId = 209,
                            CountryName = "SAO TOME AND PRINCIPE",
                            IsActive = false,
                            StrKey = "ST"
                        },
                        new
                        {
                            CountryId = 210,
                            CountryName = "EL SALVADOR",
                            IsActive = false,
                            StrKey = "SV"
                        },
                        new
                        {
                            CountryId = 211,
                            CountryName = "SINT MAARTEN (DUTCH PART)",
                            IsActive = false,
                            StrKey = "SX"
                        },
                        new
                        {
                            CountryId = 212,
                            CountryName = "SYRIAN ARAB REPUBLIC",
                            IsActive = false,
                            StrKey = "SY"
                        },
                        new
                        {
                            CountryId = 213,
                            CountryName = "ESWATINI",
                            IsActive = false,
                            StrKey = "SZ"
                        },
                        new
                        {
                            CountryId = 214,
                            CountryName = "TURKS AND CAICOS ISLANDS",
                            IsActive = false,
                            StrKey = "TC"
                        },
                        new
                        {
                            CountryId = 215,
                            CountryName = "CHAD",
                            IsActive = false,
                            StrKey = "TD"
                        },
                        new
                        {
                            CountryId = 216,
                            CountryName = "FRENCH SOUTHERN TERRITORIES",
                            IsActive = false,
                            StrKey = "TF"
                        },
                        new
                        {
                            CountryId = 217,
                            CountryName = "TOGO",
                            IsActive = false,
                            StrKey = "TG"
                        },
                        new
                        {
                            CountryId = 218,
                            CountryName = "THAILAND",
                            IsActive = false,
                            StrKey = "TH"
                        },
                        new
                        {
                            CountryId = 219,
                            CountryName = "TAJIKISTAN",
                            IsActive = false,
                            StrKey = "TJ"
                        },
                        new
                        {
                            CountryId = 220,
                            CountryName = "TOKELAU",
                            IsActive = false,
                            StrKey = "TK"
                        },
                        new
                        {
                            CountryId = 221,
                            CountryName = "TIMOR-LESTE",
                            IsActive = false,
                            StrKey = "TL"
                        },
                        new
                        {
                            CountryId = 222,
                            CountryName = "TURKMENISTAN",
                            IsActive = false,
                            StrKey = "TM"
                        },
                        new
                        {
                            CountryId = 223,
                            CountryName = "TUNISIA",
                            IsActive = false,
                            StrKey = "TN"
                        },
                        new
                        {
                            CountryId = 224,
                            CountryName = "TONGA",
                            IsActive = false,
                            StrKey = "TO"
                        },
                        new
                        {
                            CountryId = 225,
                            CountryName = "TURKEY",
                            IsActive = false,
                            StrKey = "TR"
                        },
                        new
                        {
                            CountryId = 226,
                            CountryName = "TRINIDAD AND TOBAGO",
                            IsActive = false,
                            StrKey = "TT"
                        },
                        new
                        {
                            CountryId = 227,
                            CountryName = "TUVALU",
                            IsActive = false,
                            StrKey = "TV"
                        },
                        new
                        {
                            CountryId = 228,
                            CountryName = "TAIWAN, PROVINCE OF CHINA",
                            IsActive = false,
                            StrKey = "TW"
                        },
                        new
                        {
                            CountryId = 229,
                            CountryName = "TANZANIA, UNITED REPUBLIC OF",
                            IsActive = false,
                            StrKey = "TZ"
                        },
                        new
                        {
                            CountryId = 230,
                            CountryName = "UKRAINE",
                            IsActive = false,
                            StrKey = "UA"
                        },
                        new
                        {
                            CountryId = 231,
                            CountryName = "UGANDA",
                            IsActive = false,
                            StrKey = "UG"
                        },
                        new
                        {
                            CountryId = 232,
                            CountryName = "UNITED STATES MINOR OUTLYING ISLANDS",
                            IsActive = false,
                            StrKey = "UM"
                        },
                        new
                        {
                            CountryId = 233,
                            CountryName = "UNITED STATES OF AMERICA",
                            IsActive = true,
                            StrKey = "US"
                        },
                        new
                        {
                            CountryId = 234,
                            CountryName = "URUGUAY",
                            IsActive = false,
                            StrKey = "UY"
                        },
                        new
                        {
                            CountryId = 235,
                            CountryName = "UZBEKISTAN",
                            IsActive = false,
                            StrKey = "UZ"
                        },
                        new
                        {
                            CountryId = 236,
                            CountryName = "HOLY SEE",
                            IsActive = false,
                            StrKey = "VA"
                        },
                        new
                        {
                            CountryId = 237,
                            CountryName = "SAINT VINCENT AND THE GRENADINES",
                            IsActive = false,
                            StrKey = "VC"
                        },
                        new
                        {
                            CountryId = 238,
                            CountryName = "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
                            IsActive = false,
                            StrKey = "VE"
                        },
                        new
                        {
                            CountryId = 239,
                            CountryName = "VIRGIN ISLANDS (BRITISH)",
                            IsActive = false,
                            StrKey = "VG"
                        },
                        new
                        {
                            CountryId = 240,
                            CountryName = "VIRGIN ISLANDS (U.S.)",
                            IsActive = false,
                            StrKey = "VI"
                        },
                        new
                        {
                            CountryId = 241,
                            CountryName = "VIET NAM",
                            IsActive = false,
                            StrKey = "VN"
                        },
                        new
                        {
                            CountryId = 242,
                            CountryName = "VANUATU",
                            IsActive = false,
                            StrKey = "VU"
                        },
                        new
                        {
                            CountryId = 243,
                            CountryName = "WALLIS AND FUTUNA",
                            IsActive = false,
                            StrKey = "WF"
                        },
                        new
                        {
                            CountryId = 244,
                            CountryName = "SAMOA",
                            IsActive = false,
                            StrKey = "WS"
                        },
                        new
                        {
                            CountryId = 245,
                            CountryName = "YEMEN",
                            IsActive = false,
                            StrKey = "YE"
                        },
                        new
                        {
                            CountryId = 246,
                            CountryName = "MAYOTTE",
                            IsActive = false,
                            StrKey = "YT"
                        },
                        new
                        {
                            CountryId = 247,
                            CountryName = "SOUTH AFRICA",
                            IsActive = false,
                            StrKey = "ZA"
                        },
                        new
                        {
                            CountryId = 248,
                            CountryName = "ZAMBIA",
                            IsActive = false,
                            StrKey = "ZM"
                        },
                        new
                        {
                            CountryId = 249,
                            CountryName = "ZIMBABWE",
                            IsActive = false,
                            StrKey = "ZW"
                        });
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Common.TaxOrganization", b =>
                {
                    b.Property<int>("TaxOrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxOrganizationId"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("OrgDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StrKey")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("TaxOrganizationId")
                        .HasName("PK_TaxOrganizations_TaxOrganizationId");

                    b.HasIndex("StrKey")
                        .IsUnique();

                    b.ToTable("TaxOrganizations", "Common");

                    b.HasData(
                        new
                        {
                            TaxOrganizationId = 1,
                            CountryId = 157,
                            OrgDescription = "Servicio de Administración Tributaria",
                            StrKey = "SAT"
                        },
                        new
                        {
                            TaxOrganizationId = 2,
                            CountryId = 233,
                            OrgDescription = "Internal Revenue Service",
                            StrKey = "IRS"
                        });
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Common.TaxOrganizationType", b =>
                {
                    b.Property<int>("TaxOrganizationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxOrganizationTypeId"), 1L, 1);

                    b.Property<string>("StrKey")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("TaxOrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TaxOrganizationTypeId")
                        .HasName("PK_TaxOrganizationTypes_TaxOrganizationTypeId");

                    b.HasIndex("StrKey")
                        .IsUnique();

                    b.HasIndex("TaxOrganizationId");

                    b.ToTable("TaxOrganizationTypes", "Common");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Common.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<long?>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("SaltPswd")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<bool>("SessionOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("UserBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("UserId")
                        .HasName("PK_Users_UserId");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", "Common");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            FailedAttempts = 0,
                            Password = "bbborderbox",
                            SaltPswd = "",
                            SessionOpen = false,
                            UserBlocked = false,
                            UserName = "superadmin"
                        },
                        new
                        {
                            UserId = 2L,
                            FailedAttempts = 0,
                            Password = "bbborderbox",
                            SaltPswd = "",
                            SessionOpen = false,
                            UserBlocked = false,
                            UserName = "testadmin"
                        });
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Common.UserPswdHistory", b =>
                {
                    b.Property<long>("UserPswdHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserPswdHistoryId"), 1L, 1);

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("OldPassword")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserPswdHistoryId")
                        .HasName("PK_UserPswdHistory_UserPswdHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPswdHistory", "Common");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Common.ZipCode", b =>
                {
                    b.Property<int>("ZipCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZipCodeId"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCodeVal")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("ZipCodeId")
                        .HasName("PK_ZipCodes_Id");

                    b.HasIndex("ZipCodeVal")
                        .IsUnique();

                    b.ToTable("ZipCodes", "Common");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.HR.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmployeeId"), 1L, 1);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("Birthbay")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<long>("CreatedUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<long?>("ModifiedUser")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int?>("TaxOrganizationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TaxValue")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeeId")
                        .HasName("PK_Employees_EmployeeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("TaxOrganizationTypeId");

                    b.ToTable("Employees", "HR");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.HR.EmployeeAddress", b =>
                {
                    b.Property<int>("EmployeeAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeAddressId"), 1L, 1);

                    b.Property<string>("Colony")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<long>("CreatedUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("InteriorNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<bool>("MainAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<long>("ModifiedUser")
                        .HasColumnType("bigint");

                    b.Property<string>("OutdoorNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("References")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<int>("ZipCodeId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeAddressId")
                        .HasName("PK_EmployeesAddress_Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ZipCodeId");

                    b.ToTable("EmployeesAddress", "HR");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Sales.Client", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClientId"), 1L, 1);

                    b.Property<DateTime?>("Anniversary")
                        .HasColumnType("DATE");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<long>("CreatedUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<long>("ModifiedUser")
                        .HasColumnType("bigint");

                    b.Property<int?>("TaxOrganizationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TaxValue")
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("ClientId")
                        .HasName("PK_Clients_ClientId");

                    b.HasIndex("TaxOrganizationTypeId");

                    b.ToTable("Clients", "Sales");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Sales.CustomerAddress", b =>
                {
                    b.Property<long>("CustomerAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerAddressId"), 1L, 1);

                    b.Property<bool>("BillingAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Colony")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<long>("CreatedUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("InteriorNumber")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<bool>("MainAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<long>("ModifiedUser")
                        .HasColumnType("bigint");

                    b.Property<string>("OutdoorNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("References")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<int>("ZipCodeId")
                        .HasColumnType("int");

                    b.HasKey("CustomerAddressId")
                        .HasName("PK_CustomerAddresses_CustomerAddressId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ZipCodeId");

                    b.ToTable("CustomerAddresses", "Sales");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Sales.Sale", b =>
                {
                    b.Property<long>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SaleId"), 1L, 1);

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<long>("ModifiedUser")
                        .HasColumnType("bigint");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint");

                    b.HasKey("SaleId")
                        .HasName("PK_Sales_SaleId");

                    b.HasIndex("ClientId");

                    b.HasIndex("VendorId");

                    b.ToTable("Sales", "Sales");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Shipment.Package", b =>
                {
                    b.Property<long>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PackageId"), 1L, 1);

                    b.Property<long>("CreatedUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("DATETIME");

                    b.Property<long>("ModifiedUser")
                        .HasColumnType("bigint");

                    b.Property<int>("PackageTabId")
                        .HasColumnType("int");

                    b.Property<string>("PiceId")
                        .HasColumnType("VARCHAR(21)");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint");

                    b.Property<string>("TrackNumber")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<decimal>("TrueWeight")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("PackageId")
                        .HasName("PK_Packages_PackageId");

                    b.HasIndex("PackageTabId");

                    b.HasIndex("SaleId");

                    b.ToTable("Packages", "Shipment");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Shipment.PackageTabs", b =>
                {
                    b.Property<int>("PackageTabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageTabId"), 1L, 1);

                    b.Property<long>("CreatedUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("MinWeight")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedUser")
                        .HasColumnType("bigint");

                    b.Property<long>("PackageTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("PackageTabId")
                        .HasName("PK_PackageTabs_PackageTabId");

                    b.ToTable("PackageTabs", "Shipment");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Telegram.ChatUpdate", b =>
                {
                    b.Property<long>("UpdateId")
                        .HasColumnType("bigint");

                    b.Property<long>("AppUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmployId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageText")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<bool>("NeedHuman")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ReturnResponse")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<bool>("TalkingWithHuman")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TypedCommand")
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("UpdateId")
                        .HasName("PK_ChatsUpdates_UpdateId");

                    b.ToTable("ChatsUpdates", "Telegram");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Common.TaxOrganizationType", b =>
                {
                    b.HasOne("BBBorderBox.Entity.Data.Common.TaxOrganization", null)
                        .WithMany()
                        .HasForeignKey("TaxOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TaxOrganizationTypes_TaxOrganizationId");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Common.User", b =>
                {
                    b.HasOne("BBBorderBox.Entity.Data.Common.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedUserId")
                        .HasConstraintName("FK_Users_UserId");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Common.UserPswdHistory", b =>
                {
                    b.HasOne("BBBorderBox.Entity.Data.Common.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserPswdHistory_UserId");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.HR.Employee", b =>
                {
                    b.HasOne("BBBorderBox.Entity.Data.Common.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Clients_CountryId");

                    b.HasOne("BBBorderBox.Entity.Data.Common.TaxOrganizationType", null)
                        .WithMany()
                        .HasForeignKey("TaxOrganizationTypeId")
                        .HasConstraintName("FK_Clients_TaxOrganizationTypeId");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.HR.EmployeeAddress", b =>
                {
                    b.HasOne("BBBorderBox.Entity.Data.HR.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeesAddress_EmployeeId");

                    b.HasOne("BBBorderBox.Entity.Data.Common.ZipCode", null)
                        .WithMany()
                        .HasForeignKey("ZipCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeesAddress_ZipCodeId");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Sales.Client", b =>
                {
                    b.HasOne("BBBorderBox.Entity.Data.Common.TaxOrganizationType", null)
                        .WithMany()
                        .HasForeignKey("TaxOrganizationTypeId")
                        .HasConstraintName("FK_Clients_TaxOrganizationTypeId");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Sales.CustomerAddress", b =>
                {
                    b.HasOne("BBBorderBox.Entity.Data.Sales.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerAddresses_ClientId");

                    b.HasOne("BBBorderBox.Entity.Data.Common.ZipCode", null)
                        .WithMany()
                        .HasForeignKey("ZipCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerAddresses_ZipCodeId");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Sales.Sale", b =>
                {
                    b.HasOne("BBBorderBox.Entity.Data.Sales.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Sales_ClientId");

                    b.HasOne("BBBorderBox.Entity.Data.HR.Employee", null)
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Sales_VendorId");
                });

            modelBuilder.Entity("BBBorderBox.Entity.Data.Shipment.Package", b =>
                {
                    b.HasOne("BBBorderBox.Entity.Data.Shipment.PackageTabs", null)
                        .WithMany()
                        .HasForeignKey("PackageTabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Packages_PackageTabId");

                    b.HasOne("BBBorderBox.Entity.Data.Sales.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Package_SaleId");
                });
#pragma warning restore 612, 618
        }
    }
}
